import type {
  Patient,
  Appointment,
  MedicalRecord,
  Treatment,
  Prescription,
  LabResult,
  StaffMember,
  TelemedicineSession,
  InsuranceClaim,
  EmergencyProtocol,
  MedicalHeritage,
  DashboardStats,
  AnalyticsData,
} from "./types"

// Mock Patients
export const mockPatients: Patient[] = [
  {
    id: "p1",
    name: "Adrian Higgins",
    age: 45,
    gender: "Male",
    bloodType: "O+",
    contactNumber: "555-123-4567",
    email: "adrian.higgins@example.com",
    address: "123 Main St, Anytown, CA 90210",
    insuranceProvider: "Blue Cross",
    insuranceNumber: "BC123456789",
    emergencyContact: "Mary Smith: 555-987-6543",
    registrationDate: "2022-03-15",
  },
  {
    id: "p2",
    name: "Sophia Jones",
    age: 32,
    gender: "Female",
    bloodType: "A-",
    contactNumber: "555-234-5678",
    email: "sophia.jones@example.com",
    address: "456 Oak Ave, Somewhere, NY 10001",
    insuranceProvider: "Aetna",
    insuranceNumber: "AE987654321",
    emergencyContact: "David Johnson: 555-876-5432",
    registrationDate: "2022-05-22",
  },
  {
    id: "p3",
    name: "Nikky Eve",
    age: 28,
    gender: "Female",
    bloodType: "B+",
    contactNumber: "555-345-6789",
    email: "nikky.eve@example.com",
    address: "789 Pine St, Elsewhere, TX 75001",
    insuranceProvider: "Cigna",
    insuranceNumber: "CI567891234",
    emergencyContact: "Lisa Chen: 555-765-4321",
    registrationDate: "2022-07-10",
  },
  {
    id: "p4",
    name: "Sarah Williams",
    age: 52,
    gender: "Female",
    bloodType: "AB+",
    contactNumber: "555-456-7890",
    email: "sarah.williams@example.com",
    address: "101 Elm St, Nowhere, FL 33101",
    insuranceProvider: "UnitedHealthcare",
    insuranceNumber: "UH234567891",
    emergencyContact: "Robert Williams: 555-654-3210",
    registrationDate: "2022-09-05",
  },
  {
    id: "p5",
    name: "James Rodriguez",
    age: 39,
    gender: "Male",
    bloodType: "O-",
    contactNumber: "555-567-8901",
    email: "james.rodriguez@example.com",
    address: "202 Maple Ave, Someplace, IL 60601",
    insuranceProvider: "Humana",
    insuranceNumber: "HU345678912",
    emergencyContact: "Maria Rodriguez: 555-543-2109",
    registrationDate: "2022-11-18",
  },
]

// Mock Appointments
export const mockAppointments: Appointment[] = [
  {
    id: "a1",
    patientId: "p1",
    patientName: "Adrian Higgins",
    doctorId: "d1",
    doctorName: "Dr. Evan Parker",
    date: "Jun 27, 2024",
    time: "1:02",
    duration: 30,
    status: "cancelled",
    type: "check-up",
    notes: "Annual physical examination",
  },
  {
    id: "a2",
    patientId: "p1",
    patientName: "Adrian Higgins",
    doctorId: "d2",
    doctorName: "Dr. Lana Cameron",
    date: "Jun 19, 2024",
    time: "1:01",
    duration: 45,
    status: "no-show",
    type: "follow-up",
    notes: "Follow-up on medication adjustment",
  },
  {
    id: "a3",
    patientId: "p2",
    patientName: "Sophia Jones",
    doctorId: "d3",
    doctorName: "Dr. Alex Ramirez",
    date: "Jun 20, 2024",
    time: "10:00",
    duration: 60,
    status: "no-show",
    type: "consultation",
    notes: "Initial consultation for chronic back pain",
  },
  {
    id: "a4",
    patientId: "p2",
    patientName: "Sophia Jones",
    doctorId: "d1",
    doctorName: "Dr. Evan Parker",
    date: "Jun 15, 2024",
    time: "10:55",
    duration: 30,
    status: "no-show",
    type: "check-up",
    notes: "Blood pressure monitoring",
  },
  {
    id: "a5",
    patientId: "p3",
    patientName: "Nikky Eve",
    doctorId: "d2",
    doctorName: "Dr. Lana Cameron",
    date: "Jun 15, 2024",
    time: "10:20",
    duration: 45,
    status: "no-show",
    type: "procedure",
    notes: "Minor surgical procedure - mole removal",
  },
  {
    id: "a6",
    patientId: "p3",
    patientName: "Nikky Eve",
    doctorId: "d2",
    doctorName: "Dr. Lana Cameron",
    date: "Jun 12, 2024",
    time: "12:30",
    duration: 45,
    status: "scheduled",
    type: "procedure",
    notes: "Minor surgical procedure - mole removal",
  },
]

// Mock Medical Records
export const mockMedicalRecords: MedicalRecord[] = [
  {
    id: "mr1",
    patientId: "p1",
    patientName: "John Smith",
    date: "2022-12-10",
    doctorId: "d1",
    doctorName: "Dr. Elizabeth Taylor",
    diagnosis: "Hypertension",
    symptoms: ["Headache", "Dizziness", "Fatigue"],
    notes: "Patient presents with elevated blood pressure. Prescribed lisinopril 10mg daily.",
    attachments: ["bp_chart.pdf", "ecg_results.pdf"],
  },
  {
    id: "mr2",
    patientId: "p2",
    patientName: "Emily Johnson",
    date: "2023-01-15",
    doctorId: "d2",
    doctorName: "Dr. Robert Brown",
    diagnosis: "Migraine",
    symptoms: ["Severe headache", "Nausea", "Light sensitivity"],
    notes: "Patient reports recurring migraines. Prescribed sumatriptan as needed.",
    attachments: ["headache_diary.pdf"],
  },
  {
    id: "mr3",
    patientId: "p3",
    patientName: "Michael Chen",
    date: "2023-02-05",
    doctorId: "d3",
    doctorName: "Dr. Jennifer Wilson",
    diagnosis: "Lumbar strain",
    symptoms: ["Lower back pain", "Limited mobility", "Pain when bending"],
    notes: "Patient injured back while lifting heavy object. Prescribed muscle relaxants and physical therapy.",
    attachments: ["xray_results.pdf", "pt_referral.pdf"],
  },
  {
    id: "mr4",
    patientId: "p4",
    patientName: "Sarah Williams",
    date: "2023-02-20",
    doctorId: "d1",
    doctorName: "Dr. Elizabeth Taylor",
    diagnosis: "Type 2 Diabetes",
    symptoms: ["Increased thirst", "Frequent urination", "Fatigue"],
    notes: "Patient diagnosed with Type 2 Diabetes. Started on metformin 500mg twice daily.",
    attachments: ["lab_results.pdf", "glucose_monitor_prescription.pdf"],
  },
  {
    id: "mr5",
    patientId: "p5",
    patientName: "James Rodriguez",
    date: "2023-03-01",
    doctorId: "d2",
    doctorName: "Dr. Robert Brown",
    diagnosis: "Suspicious mole",
    symptoms: ["Changing mole appearance", "Irregular borders"],
    notes: "Patient has suspicious mole on upper back. Scheduled for removal and biopsy.",
    attachments: ["dermatology_photos.pdf", "procedure_consent.pdf"],
  },
]

// Mock Treatments
export const mockTreatments: Treatment[] = [
  {
    id: "t1",
    patientId: "p1",
    patientName: "John Smith",
    condition: "Hypertension",
    treatmentPlan: "Medication therapy with lisinopril 10mg daily, dietary sodium restriction, regular exercise",
    startDate: "2022-12-10",
    endDate: "2023-06-10",
    status: "active",
    notes: "Patient responding well to medication. Blood pressure trending downward.",
  },
  {
    id: "t2",
    patientId: "p2",
    patientName: "Emily Johnson",
    condition: "Migraine",
    treatmentPlan: "Sumatriptan as needed for acute attacks, trigger avoidance, stress management techniques",
    startDate: "2023-01-15",
    endDate: "2023-07-15",
    status: "active",
    notes: "Patient reports reduced frequency of migraines with medication and lifestyle changes.",
  },
  {
    id: "t3",
    patientId: "p3",
    patientName: "Michael Chen",
    condition: "Lumbar strain",
    treatmentPlan: "Physical therapy 2x weekly for 6 weeks, cyclobenzaprine 5mg as needed for muscle spasms",
    startDate: "2023-02-05",
    endDate: "2023-03-19",
    status: "active",
    notes: "Patient showing improvement with physical therapy. Pain levels decreasing.",
  },
  {
    id: "t4",
    patientId: "p4",
    patientName: "Sarah Williams",
    condition: "Type 2 Diabetes",
    treatmentPlan: "Metformin 500mg twice daily, carbohydrate-controlled diet, daily exercise, glucose monitoring",
    startDate: "2023-02-20",
    endDate: "2023-08-20",
    status: "active",
    notes: "Patient adjusting well to medication. Blood glucose levels improving.",
  },
  {
    id: "t5",
    patientId: "p5",
    patientName: "James Rodriguez",
    condition: "Suspicious mole",
    treatmentPlan: "Surgical excision with pathology analysis, follow-up examination in 2 weeks",
    startDate: "2023-03-01",
    endDate: "2023-03-15",
    status: "active",
    notes: "Procedure scheduled for March 21. Patient understands post-procedure care instructions.",
  },
]

// Mock Prescriptions
export const mockPrescriptions: Prescription[] = [
  {
    id: "rx1",
    patientId: "p1",
    patientName: "John Smith",
    doctorId: "d1",
    doctorName: "Dr. Elizabeth Taylor",
    medicationName: "Lisinopril",
    dosage: "10mg",
    frequency: "Once daily",
    startDate: "2022-12-10",
    endDate: "2023-06-10",
    refills: 5,
    status: "active",
    notes: "Take in the morning with food.",
  },
  {
    id: "rx2",
    patientId: "p2",
    patientName: "Emily Johnson",
    doctorId: "d2",
    doctorName: "Dr. Robert Brown",
    medicationName: "Sumatriptan",
    dosage: "50mg",
    frequency: "As needed for migraine attacks",
    startDate: "2023-01-15",
    endDate: "2023-07-15",
    refills: 3,
    status: "active",
    notes: "Take at first sign of migraine. Do not exceed 200mg in 24 hours.",
  },
  {
    id: "rx3",
    patientId: "p3",
    patientName: "Michael Chen",
    doctorId: "d3",
    doctorName: "Dr. Jennifer Wilson",
    medicationName: "Cyclobenzaprine",
    dosage: "5mg",
    frequency: "Three times daily as needed",
    startDate: "2023-02-05",
    endDate: "2023-03-05",
    refills: 0,
    status: "active",
    notes: "May cause drowsiness. Do not drive or operate machinery.",
  },
  {
    id: "rx4",
    patientId: "p4",
    patientName: "Sarah Williams",
    doctorId: "d1",
    doctorName: "Dr. Elizabeth Taylor",
    medicationName: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily with meals",
    startDate: "2023-02-20",
    endDate: "2023-08-20",
    refills: 5,
    status: "active",
    notes: "Take with food to minimize gastrointestinal side effects.",
  },
  {
    id: "rx5",
    patientId: "p5",
    patientName: "James Rodriguez",
    doctorId: "d2",
    doctorName: "Dr. Robert Brown",
    medicationName: "Cephalexin",
    dosage: "500mg",
    frequency: "Four times daily",
    startDate: "2023-03-21",
    endDate: "2023-03-28",
    refills: 0,
    status: "active",
    notes: "Antibiotic to prevent infection after procedure. Complete entire course.",
  },
]

// Mock Lab Results
export const mockLabResults: LabResult[] = [
  {
    id: "lr1",
    patientId: "p1",
    patientName: "John Smith",
    testName: "Complete Blood Count (CBC)",
    testDate: "2022-12-05",
    resultDate: "2022-12-07",
    result: "WBC: 7.2, RBC: 4.8, Hemoglobin: 14.5, Hematocrit: 42%, Platelets: 250",
    normalRange: "WBC: 4.5-11.0, RBC: 4.5-5.9, Hemoglobin: 13.5-17.5, Hematocrit: 41-50%, Platelets: 150-450",
    status: "normal",
    notes: "All values within normal range.",
  },
  {
    id: "lr2",
    patientId: "p1",
    patientName: "John Smith",
    testName: "Lipid Panel",
    testDate: "2022-12-05",
    resultDate: "2022-12-07",
    result: "Total Cholesterol: 220, HDL: 45, LDL: 145, Triglycerides: 150",
    normalRange: "Total Cholesterol: <200, HDL: >40, LDL: <130, Triglycerides: <150",
    status: "abnormal",
    notes: "Elevated total cholesterol and LDL. Recommend dietary changes and follow-up testing in 3 months.",
  },
  {
    id: "lr3",
    patientId: "p4",
    patientName: "Sarah Williams",
    testName: "Hemoglobin A1C",
    testDate: "2023-02-15",
    resultDate: "2023-02-17",
    result: "7.2%",
    normalRange: "<5.7% normal, 5.7-6.4% prediabetes, >6.5% diabetes",
    status: "abnormal",
    notes: "Consistent with Type 2 Diabetes diagnosis. Recommend medication and lifestyle modifications.",
  },
  {
    id: "lr4",
    patientId: "p4",
    patientName: "Sarah Williams",
    testName: "Fasting Blood Glucose",
    testDate: "2023-02-15",
    resultDate: "2023-02-16",
    result: "142 mg/dL",
    normalRange: "70-99 mg/dL normal, 100-125 mg/dL prediabetes, >126 mg/dL diabetes",
    status: "abnormal",
    notes: "Elevated blood glucose consistent with diabetes diagnosis. Correlates with elevated A1C.",
  },
  {
    id: "lr5",
    patientId: "p5",
    patientName: "James Rodriguez",
    testName: "Skin Biopsy",
    testDate: "2023-03-21",
    resultDate: "2023-03-25",
    result: "Pending",
    normalRange: "N/A",
    status: "normal",
    notes: "Specimen sent to pathology. Results expected within 5-7 business days.",
  },
]

// Mock Staff Members
export const mockStaffMembers: StaffMember[] = [
  {
    id: "d1",
    name: "Dr. Elizabeth Taylor",
    role: "Physician",
    department: "Internal Medicine",
    contactNumber: "555-111-2222",
    email: "elizabeth.taylor@medicare.com",
    startDate: "2018-05-15",
    status: "active",
  },
  {
    id: "d2",
    name: "Dr. Robert Brown",
    role: "Physician",
    department: "Dermatology",
    contactNumber: "555-222-3333",
    email: "robert.brown@medicare.com",
    startDate: "2019-03-10",
    status: "active",
  },
  {
    id: "d3",
    name: "Dr. Jennifer Wilson",
    role: "Physician",
    department: "Orthopedics",
    contactNumber: "555-333-4444",
    email: "jennifer.wilson@medicare.com",
    startDate: "2020-01-20",
    status: "active",
  },
  {
    id: "n1",
    name: "Sarah Johnson",
    role: "Registered Nurse",
    department: "Internal Medicine",
    contactNumber: "555-444-5555",
    email: "sarah.johnson@medicare.com",
    startDate: "2019-07-12",
    status: "active",
  },
  {
    id: "n2",
    name: "Michael Davis",
    role: "Registered Nurse",
    department: "Orthopedics",
    contactNumber: "555-555-6666",
    email: "michael.davis@medicare.com",
    startDate: "2020-09-05",
    status: "active",
  },
  {
    id: "a1",
    name: "Jessica Martinez",
    role: "Medical Assistant",
    department: "Dermatology",
    contactNumber: "555-666-7777",
    email: "jessica.martinez@medicare.com",
    startDate: "2021-02-15",
    status: "active",
  },
  {
    id: "r1",
    name: "David Wilson",
    role: "Receptionist",
    department: "Front Desk",
    contactNumber: "555-777-8888",
    email: "david.wilson@medicare.com",
    startDate: "2021-06-10",
    status: "active",
  },
]

// Mock Telemedicine Sessions
export const mockTelemedicineSessions: TelemedicineSession[] = [
  {
    id: "ts1",
    patientId: "p2",
    patientName: "Emily Johnson",
    doctorId: "d2",
    doctorName: "Dr. Robert Brown",
    date: "2023-03-22",
    time: "10:00",
    duration: 30,
    status: "scheduled",
    notes: "Follow-up on migraine treatment",
  },
  {
    id: "ts2",
    patientId: "p3",
    patientName: "Michael Chen",
    doctorId: "d3",
    doctorName: "Dr. Jennifer Wilson",
    date: "2023-03-23",
    time: "14:30",
    duration: 30,
    status: "scheduled",
    notes: "Review physical therapy progress",
  },
  {
    id: "ts3",
    patientId: "p4",
    patientName: "Sarah Williams",
    doctorId: "d1",
    doctorName: "Dr. Elizabeth Taylor",
    date: "2023-03-24",
    time: "09:15",
    duration: 30,
    status: "scheduled",
    notes: "Diabetes management check-in",
  },
]

// Mock Insurance Claims
export const mockInsuranceClaims: InsuranceClaim[] = [
  {
    id: "ic1",
    patientId: "p1",
    patientName: "John Smith",
    insuranceProvider: "Blue Cross",
    policyNumber: "BC123456789",
    serviceDate: "2022-12-10",
    claimDate: "2022-12-12",
    amount: 150.0,
    status: "paid",
    notes: "Office visit and blood work",
  },
  {
    id: "ic2",
    patientId: "p2",
    patientName: "Emily Johnson",
    insuranceProvider: "Aetna",
    policyNumber: "AE987654321",
    serviceDate: "2023-01-15",
    claimDate: "2023-01-16",
    amount: 125.0,
    status: "paid",
    notes: "Office visit for migraine consultation",
  },
  {
    id: "ic3",
    patientId: "p3",
    patientName: "Michael Chen",
    insuranceProvider: "Cigna",
    policyNumber: "CI567891234",
    serviceDate: "2023-02-05",
    claimDate: "2023-02-06",
    amount: 200.0,
    status: "in-review",
    notes: "Office visit and X-rays",
  },
  {
    id: "ic4",
    patientId: "p4",
    patientName: "Sarah Williams",
    insuranceProvider: "UnitedHealthcare",
    policyNumber: "UH234567891",
    serviceDate: "2023-02-20",
    claimDate: "2023-02-21",
    amount: 175.0,
    status: "submitted",
    notes: "Office visit and lab work",
  },
  {
    id: "ic5",
    patientId: "p5",
    patientName: "James Rodriguez",
    insuranceProvider: "Humana",
    policyNumber: "HU345678912",
    serviceDate: "2023-03-01",
    claimDate: "2023-03-02",
    amount: 150.0,
    status: "paid",
    notes: "Dermatology consultation",
  },
]

// Mock Emergency Protocols
export const mockEmergencyProtocols: EmergencyProtocol[] = [
  {
    id: "ep1",
    title: "Code Blue - Cardiac Arrest",
    description: "Protocol for responding to cardiac arrest emergencies",
    steps: [
      "Call for help and activate Code Blue",
      "Begin CPR immediately",
      "Retrieve and apply AED/defibrillator",
      "Establish IV access",
      "Administer emergency medications as directed",
      "Document all interventions and times",
    ],
    lastUpdated: "2022-11-15",
    responsibleStaff: ["All clinical staff"],
  },
  {
    id: "ep2",
    title: "Anaphylactic Reaction",
    description: "Protocol for managing severe allergic reactions",
    steps: [
      "Assess airway, breathing, circulation",
      "Administer epinephrine via auto-injector or as directed",
      "Place patient in supine position with legs elevated",
      "Administer oxygen if available",
      "Monitor vital signs",
      "Arrange for emergency transport if in outpatient setting",
    ],
    lastUpdated: "2022-12-10",
    responsibleStaff: ["All clinical staff"],
  },
  {
    id: "ep3",
    title: "Stroke Alert",
    description: "Protocol for rapid assessment and management of potential stroke",
    steps: [
      "Perform FAST assessment (Face, Arms, Speech, Time)",
      "Notify stroke team immediately",
      "Check blood glucose",
      "Obtain rapid CT scan",
      "Determine time of symptom onset",
      "Prepare for potential thrombolytic therapy",
    ],
    lastUpdated: "2023-01-20",
    responsibleStaff: ["Emergency Department Staff", "Neurology Team"],
  },
]

// Mock Medical Heritage
export const mockMedicalHeritage: MedicalHeritage[] = [
  {
    id: "mh1",
    patientId: "p1",
    patientName: "John Smith",
    familyMember: "Father",
    relationship: "First-degree relative",
    condition: "Hypertension",
    diagnosisAge: 50,
    status: "deceased",
    notes: "Father had complications from hypertension leading to stroke at age 65",
  },
  {
    id: "mh2",
    patientId: "p1",
    patientName: "John Smith",
    familyMember: "Mother",
    relationship: "First-degree relative",
    condition: "Type 2 Diabetes",
    diagnosisAge: 55,
    status: "managed",
    notes: "Mother currently managing diabetes with medication and diet",
  },
  {
    id: "mh3",
    patientId: "p2",
    patientName: "Emily Johnson",
    familyMember: "Mother",
    relationship: "First-degree relative",
    condition: "Migraine",
    diagnosisAge: 30,
    status: "managed",
    notes: "Mother has history of migraines similar to patient",
  },
  {
    id: "mh4",
    patientId: "p4",
    patientName: "Sarah Williams",
    familyMember: "Father",
    relationship: "First-degree relative",
    condition: "Type 2 Diabetes",
    diagnosisAge: 45,
    status: "deceased",
    notes: "Father had complications from diabetes including kidney disease",
  },
  {
    id: "mh5",
    patientId: "p4",
    patientName: "Sarah Williams",
    familyMember: "Sister",
    relationship: "First-degree relative",
    condition: "Type 2 Diabetes",
    diagnosisAge: 48,
    status: "active",
    notes: "Sister diagnosed with diabetes 2 years ago",
  },
  {
    id: "mh6",
    patientId: "p5",
    patientName: "James Rodriguez",
    familyMember: "Uncle",
    relationship: "Second-degree relative",
    condition: "Melanoma",
    diagnosisAge: 52,
    status: "deceased",
    notes: "Maternal uncle died from metastatic melanoma",
  },
]

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalPatients: 1248,
  appointmentsToday: 24,
  pendingLabResults: 7,
  activeTreatments: 42,
  recentRegistrations: 15,
  upcomingAppointments: 87,
}

// Mock Analytics Data
export const mockAnalyticsData: AnalyticsData = {
  patientsByAge: [
    { ageRange: "0-17", count: 187 },
    { ageRange: "18-34", count: 342 },
    { ageRange: "35-50", count: 415 },
    { ageRange: "51-65", count: 203 },
    { ageRange: "66+", count: 101 },
  ],
  appointmentsByType: [
    { type: "Check-up", count: 423 },
    { type: "Follow-up", count: 287 },
    { type: "Emergency", count: 56 },
    { type: "Consultation", count: 178 },
    { type: "Procedure", count: 104 },
  ],
  treatmentSuccess: [
    { condition: "Hypertension", successRate: 78 },
    { condition: "Diabetes", successRate: 65 },
    { condition: "Asthma", successRate: 82 },
    { condition: "Depression", successRate: 71 },
    { condition: "Arthritis", successRate: 68 },
  ],
  revenueByMonth: [
    { month: "Jan", amount: 125000 },
    { month: "Feb", amount: 132000 },
    { month: "Mar", amount: 141000 },
    { month: "Apr", amount: 138000 },
    { month: "May", amount: 145000 },
    { month: "Jun", amount: 152000 },
    { month: "Jul", amount: 149000 },
    { month: "Aug", amount: 156000 },
    { month: "Sep", amount: 163000 },
    { month: "Oct", amount: 159000 },
    { month: "Nov", amount: 167000 },
    { month: "Dec", amount: 172000 },
  ],
}

